name: Build Releases

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:     
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Set environment variables
        run: echo "VERSION=$(cat version)" >> $GITHUB_ENV
      - name: Update version number in About
        run: |
          sed -i -e 's|<td id="version">\(.*\)</td>|<td id="version">'"v${{ env.VERSION }}"'</td>|g'  src/pages/config.html
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install htmlmin esptool
      - name: Minify HTML files
        run: python .github/workflows/shrinkHTML.py
        shell: sh
      - name: Build ESP32 firmware
        run: platformio run -e esp32dev
      - name: Build one binary for ESP32
        run: |
          folder=.pio/build/esp32dev
          chip=esp32
          mv $folder/firmware.bin $folder/${chip}nat_extended_v${{ env.VERSION }}.bin
          esptool.py --chip $chip merge_bin -o $folder/${chip}nat_extended_full_v${{ env.VERSION }}.bin --flash_freq keep --flash_size keep 0x1000 $folder/bootloader.bin 0x10000 $folder/${chip}nat_extended_v${{ env.VERSION }}.bin 0x8000 $folder/partitions.bin
          mkdir -p release
          zip -j release/${chip}nat_extended_update_v${{ env.VERSION }}.zip $folder/${chip}nat_extended_v${{ env.VERSION }}.bin
          zip -j release/${chip}nat_extended_full_v${{ env.VERSION }}.zip $folder/${chip}nat_extended_full_v${{ env.VERSION }}.bin

      - name: Build ESP32 C3 firmware
        run: platformio run -e esp32-c3-devkitm-1
      - name: Build one binary for ESP32 C3
        run: |
          folder=.pio/build/esp32-c3-devkitm-1
          chip=esp32c3
          mv $folder/firmware.bin $folder/${chip}nat_extended_v${{ env.VERSION }}.bin
          esptool.py --chip $chip merge_bin -o $folder/${chip}nat_extended_full_v${{ env.VERSION }}.bin --flash_freq keep --flash_size keep 0x0 $folder/bootloader.bin 0x10000 $folder/${chip}nat_extended_v${{ env.VERSION }}.bin 0x8000 $folder/partitions.bin
          mkdir -p release
          zip -j release/${chip}nat_extended_update_v${{ env.VERSION }}.zip $folder/${chip}nat_extended_v${{ env.VERSION }}.bin
          zip -j release/${chip}nat_extended_full_v${{ env.VERSION }}.zip $folder/${chip}nat_extended_full_v${{ env.VERSION }}.bin
      - name: Build ESP32 S2 firmware
        run: platformio run -e featheresp32-s2
      - name: Build one binary for ESP32 S2
        run: |
          folder=.pio/build/featheresp32-s2
          chip=esp32s2
          mv $folder/firmware.bin $folder/${chip}nat_extended_v${{ env.VERSION }}.bin
          esptool.py --chip $chip merge_bin -o $folder/${chip}nat_extended_full_v${{ env.VERSION }}.bin --flash_freq keep --flash_size keep 0x1000 $folder/bootloader.bin 0x10000 $folder/${chip}nat_extended_v${{ env.VERSION }}.bin 0x8000 $folder/partitions.bin
          mkdir -p release
          zip -j release/${chip}nat_extended_update_v${{ env.VERSION }}.zip $folder/${chip}nat_extended_v${{ env.VERSION }}.bin
          zip -j release/${chip}nat_extended_full_v${{ env.VERSION }}.zip $folder/${chip}nat_extended_full_v${{ env.VERSION }}.bin

      - name: Delete old drafts
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create draft release
        uses: "marvinpinto/action-automatic-releases@latest"
        if: github.ref == 'refs/heads/master'
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          automatic_release_tag: v${{ env.VERSION }}
          title: v${{ env.VERSION }}
          files: |
            release/*.zip
